### ISSUE TITLE
[Question] How far is the development? Can I contribute ?

### ISSUE THREAD

**Issue by arunavo4** [p-zombie/freqtrade#1]
Hi this project looks very interesting. I have worked with Rllib a lot before and with the Tensortrade Library. This repo does need a basic readme. 
Also, if you need extra hands I would like to contribute if and when possible.

**Comment by joaorafaelm** [comment]
Hi there, I'm actively working on it, this repo was moved here from https://github.com/joaorafaelm/freqtrade-heroku

Right now I'm working on migrating the infra to vultr with terraform and automatic deploys using github actions.

The project is pretty easy to setup, you basically clone it on your local, create an .env file (and define these vars: EXCHANGE_NAME=binance
EXCHANGE_KEY=your key
EXCHANGE_SECRET=your secret) at the root of the repo, then you can run make build and you should be able to use any command in the makefile, backtest, hyperopt etc.

As for the RL strategy, you just need to run make gym to start the open ai gym env, the config used in the gym is user_data/config.test.json, you can see a gym section there, where you can change the timerange. I still need to work on improving the env policy, currently the performance is not great, its just a baseline. Also, It takes some time to startup cause of the way backtest data is loaded. 
Once you train the rl agent you can use freqtrade bultin backtest to validate the model against any timerange https://github.com/p-zombie/freqtrade/blob/master/user_data/strategies/GymStrategy.py
