### ISSUE TITLE
How do I run this

### ISSUE THREAD

**Issue by Cryptoseen** [p-zombie/freqtrade#2]
Did I copy it to my own computer? The name of the file is freqtrade-master. So how do I run this? What codes should I write? Can you write step by step? I'm not a programmer, I'm using ubuntu 18.4. Thank you

**Comment by joaorafaelm** [comment]
Hi, I added some details in this issue https://github.com/p-zombie/freqtrade/issues/1

I'll write a detailed readme later this week

**Comment by joaorafaelm** [comment]
added more details in https://github.com/p-zombie/freqtrade/pull/5
