### ISSUE TITLE
rnn

### ISSUE THREAD

**Issue by brusand** [p-zombie/freqtrade#3]
hy did you test the Lstm policy ?   
#from stable_baselines3.common.evaluation import MlpLstmPolicy

How to be profitable, i tried both freqtradegym and your version and both generate one buy , one sell and a big loss lollll. I even try the gym on the same coin on the same period and get big losss. How to improve it ?

thx
Bruno

**Comment by joaorafaelm** [comment]
hi @brusand I did not test other policies, and they are defnitely not profitable, I gave up training it because it was too slow and I never had decent results

**Comment by joaorafaelm** [comment]
I recommend this repo https://github.com/hugocen/freqtrade-gym
All the RL files are originaly fom that repo, I only modified and fixed minor bugs to make it runnable
